# Site settings
title: Hailey M. Mahan
email: hailey.mahan@gmail.com
description: "Just a blog with my thoughts on code, food, old movies, journalism and other fun things."
baseurl: "/hmahan.github.io"
url: "http://hmahan.github.io"
twitter_username: haileymmahan
github_username:  hmahan

# Build settings
markdown: kramdown
permalink: pretty
