# Site settings
title: Hailey M. Mahan
email: hailey.mahan@gmail.com
description: "Amazing thoughts about about amazing things like code, food, cocktails, old movies and journalism."
url: "http://hmahan.github.io"
twitter_username: HaileyMMahan
github_username:  hmahan

# Build settings
markdown: kramdown
permalink: pretty
